# .github/workflows/release.yml

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Build
       id: compile
       uses: heroku/rust-cargo-musl-action@v1
       with:
         command: 'build'
     - name: Copy .env File
       uses: canastro/copy-file-action@master
       with:
        source: ".env.example"
        target: ${{ steps.compile.outputs.release-dir }}.env
     - name: Copy templates directory
       uses: canastro/copy-file-action@master
       with:
        source: "templates/"
        flags: -r
        target: ${{ steps.compile.outputs.release-dir }}
     - name: Copy statics directory
       uses: canastro/copy-file-action@master
       with:
        source: "statics/"
        flags: -r
        target: ${{ steps.compile.outputs.release-dir }}
     - name: Install Zip
       uses: montudor/action-zip@v1
     - name: Zip Files
       run: zip -qq -r publish.zip templates/ statics/ sunrun-rs .env
       working-directory: ${{ steps.compile.outputs.release-dir }}
     - name: Publish
       uses: softprops/action-gh-release@v1
       with: 
         files: publish.zip
         tag_name: Autorelease-v${{ github.run_number }}
