# .github/workflows/release.yml

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Build
       id: compile
       uses: heroku/rust-cargo-musl-action@v1
       with:
         command: 'build'
     - name: Copy Executable File
       uses: canastro/copy-file-action@master
       with:
        source: ${{ steps.compile.outputs.release-dir }}sunrun-rs
        target: sunrun-rs
     - name: Rename .env File
       uses: canastro/copy-file-action@master
       with:
        source: .env.example
        target: .env
     - name: Install Zip
       uses: montudor/action-zip@v1
     - name: Zip Files
       run: zip -qq -r publish.zip templates/ statics/ sunrun-rs .env
     - name: Zip Update Files
       run: zip -qq -r publish_update.zip templates/ statics/ sunrun-rs
     - name: Publish
       uses: softprops/action-gh-release@v1
       with: 
         files: |
           publish.zip
           publish_update.zip
           sunrun-rs
         tag_name: Autorelease-v${{ github.run_number }}
